import json

json_data = '''
{
    "materials": [
        {
            "Family": "Metals",
            "Subfamily": "Metal",
            "Tier": "T1",
            "Material_ID": "Cu",
            "Name": "Copper",
            "Defense_Slash": 0.1734,
            "Defense_Pierce": 0.10011,
            "Defense_Blunt": 0.5939,
            "Element_Fire": 0.12903,
            "Element_Water": 0.26667,
            "Element_Wind": 0.064935,
            "Element_Earth": 0.40261,
            "Toughness": 210
        },
        {
            "Family": "Metals",
            "Subfamily": "Metal",
            "Tier": "T1",
            "Material_ID": "Fe",
            "Name": "Iron",
            "Defense_Slash": 0.43088,
            "Defense_Pierce": 0.19794,
            "Defense_Blunt": 0.4957,
            "Element_Fire": 0.59179,
            "Element_Water": 0.0,
            "Element_Wind": 0.86039,
            "Element_Earth": 0.40554,
            "Toughness": 540
        },
        {
            "Family": "Metals",
            "Subfamily": "Metal",
            "Tier": "T1",
            "Material_ID": "Sn",
            "Name": "Tin",
            "Defense_Slash": 0.0,
            "Defense_Pierce": 0.0,
            "Defense_Blunt": 0.53344,
            "Element_Fire": 0.69377,
            "Element_Water": 0.26667,
            "Element_Wind": 0.87662,
            "Element_Earth": 0.1744,
            "Toughness": 15
        },
        {
            "Family": "Metals",
            "Subfamily": "Metal",
            "Tier": "T1",
            "Material_ID": "Pb",
            "Name": "Lead",
            "Defense_Slash": 0.00041,
            "Defense_Pierce": 0.00213,
            "Defense_Blunt": 0.55,
            "Element_Fire": 0.3,
            "Element_Water": 0.0,
            "Element_Wind": 0.97,
            "Element_Earth": 0.3,
            "Toughness": 12
        },
        {
            "Family": "Metals",
            "Subfamily": "Metal",
            "Tier": "T1",
            "Material_ID": "Ag",
            "Name": "Silver",
            "Defense_Slash": 0.1029,
            "Defense_Pierce": 0.02953,
            "Defense_Blunt": 0.55047,
            "Element_Fire": 0.16,
            "Element_Water": 0.53333,
            "Element_Wind": 0.0,
            "Element_Earth": 0.3415,
            "Toughness": 150
        },
        {
            "Family": "Metals",
            "Subfamily": "Metal",
            "Tier": "T1",
            "Material_ID": "Au",
            "Name": "Gold",
            "Defense_Slash": 0.0865,
            "Defense_Pierce": 0.03125,
            "Defense_Blunt": 0.52405,
            "Element_Fire": 0.48937,
            "Element_Water": 1.0,
            "Element_Wind": 0.29221,
            "Element_Earth": 0.57143,
            "Toughness": 120
        },
        {
            "Family": "Metals",
            "Subfamily": "Metal",
            "Tier": "T1",
            "Material_ID": "Zn",
            "Name": "Zinc",
            "Defense_Slash": 0.22015,
            "Defense_Pierce": 0.1111,
            "Defense_Blunt": 0.48251,
            "Element_Fire": 0.65092,
            "Element_Water": 0.4,
            "Element_Wind": 0.74675,
            "Element_Earth": 0.205,
            "Toughness": 110
        },
        {
            "Family": "Metals",
            "Subfamily": "Metal",
            "Tier": "T1",
            "Material_ID": "Ni",
            "Name": "Nickel",
            "Defense_Slash": 0.53747,
            "Defense_Pierce": 0.2643,
            "Defense_Blunt": 0.51146,
            "Element_Fire": 0.73319,
            "Element_Water": 0.53333,
            "Element_Wind": 0.79545,
            "Element_Earth": 0.43652,
            "Toughness": 480
        },
        {
            "Family": "Metals",
            "Subfamily": "Metal",
            "Tier": "T1",
            "Material_ID": "Al",
            "Name": "Aluminum",
            "Defense_Slash": 0.48581,
            "Defense_Pierce": 0.21711,
            "Defense_Blunt": 0.60266,
            "Element_Fire": 0.52971,
            "Element_Water": 0.66667,
            "Element_Wind": 0.42208,
            "Element_Earth": 0.14286,
            "Toughness": 90
        },
        {
            "Family": "Metals",
            "Subfamily": "Alloy",
            "Tier": "T2",
            "Material_ID": "Bronze",
            "Name": "Bronze (Cu+Sn)",
            "Defense_Slash": 0.37184,
            "Defense_Pierce": 0.19914,
            "Defense_Blunt": 0.65469,
            "Element_Fire": 0.7456,
            "Element_Water": 0.4,
            "Element_Wind": 0.90909,
            "Element_Earth": 0.43351,
            "Toughness": 241
        },
        {
            "Family": "Metals",
            "Subfamily": "Alloy",
            "Tier": "T2",
            "Material_ID": "Brass",
            "Name": "Brass (Cu+Zn)",
            "Defense_Slash": 0.31608,
            "Defense_Pierce": 0.13449,
            "Defense_Blunt": 0.5904,
            "Element_Fire": 0.68415,
            "Element_Water": 0.53333,
            "Element_Wind": 0.77922,
            "Element_Earth": 0.35306,
            "Toughness": 350
        },
        {
            "Family": "Metals",
            "Subfamily": "Alloy",
            "Tier": "T2",
            "Material_ID": "Pewter",
            "Name": "Pewter (Sn+Pb/Cu)",
            "Defense_Slash": 0.03649,
            "Defense_Pierce": 0.02919,
            "Defense_Blunt": 0.52628,
            "Element_Fire": 0.82787,
            "Element_Water": 0.53333,
            "Element_Wind": 0.94156,
            "Element_Earth": 0.18012,
            "Toughness": 15
        },
        {
            "Family": "Metals",
            "Subfamily": "Alloy",
            "Tier": "T2",
            "Material_ID": "WroughtFe",
            "Name": "Wrought Iron",
            "Defense_Slash": 0.23655,
            "Defense_Pierce": 0.11783,
            "Defense_Blunt": 0.55792,
            "Element_Fire": 0.67179,
            "Element_Water": 0.26667,
            "Element_Wind": 0.86039,
            "Element_Earth": 0.43914,
            "Toughness": 345
        },
        {
            "Family": "Metals",
            "Subfamily": "Alloy",
            "Tier": "T3",
            "Material_ID": "CastFe",
            "Name": "Cast Iron",
            "Defense_Slash": 0.16358,
            "Defense_Pierce": 0.27351,
            "Defense_Blunt": 0.51179,
            "Element_Fire": 0.71406,
            "Element_Water": 0.26667,
            "Element_Wind": 0.92532,
            "Element_Earth": 0.2335,
            "Toughness": 172
        },
        {
            "Family": "Metals",
            "Subfamily": "Alloy",
            "Tier": "T3",
            "Material_ID": "CarbonSteel",
            "Name": "Carbon Steel",
            "Defense_Slash": 0.34888,
            "Defense_Pierce": 0.17024,
            "Defense_Blunt": 0.59356,
            "Element_Fire": 0.68251,
            "Element_Water": 0.13333,
            "Element_Wind": 0.92532,
            "Element_Earth": 0.51208,
            "Toughness": 620
        },
        {
            "Family": "Metals",
            "Subfamily": "Alloy",
            "Tier": "T3",
            "Material_ID": "Damascus",
            "Name": "Damascus Steel",
            "Defense_Slash": 0.68507,
            "Defense_Pierce": 1.0,
            "Defense_Blunt": 0.63287,
            "Element_Fire": 0.71097,
            "Element_Water": 0.2,
            "Element_Wind": 0.92532,
            "Element_Earth": 0.54779,
            "Toughness": 930
        },
        {
            "Family": "Metals",
            "Subfamily": "Alloy",
            "Tier": "T4",
            "Material_ID": "Stainless",
            "Name": "Stainless Steel",
            "Defense_Slash": 0.56822,
            "Defense_Pierce": 0.19794,
            "Defense_Blunt": 0.67217,
            "Element_Fire": 1.0,
            "Element_Water": 1.0,
            "Element_Wind": 1.0,
            "Element_Earth": 0.58501,
            "Toughness": 655
        },
        {
            "Family": "Metals",
            "Subfamily": "Alloy",
            "Tier": "T4",
            "Material_ID": "ToolSteel",
            "Name": "Tool Steel",
            "Defense_Slash": 1.0,
            "Defense_Pierce": 0.49656,
            "Defense_Blunt": 0.62571,
            "Element_Fire": 0.87633,
            "Element_Water": 0.66667,
            "Element_Wind": 0.94156,
            "Element_Earth": 0.54779,
            "Toughness": 2070
        },
        {
            "Family": "Metals",
            "Subfamily": "Alloy",
            "Tier": "T4",
            "Material_ID": "Ti",
            "Name": "Titanium",
            "Defense_Slash": 0.76706,
            "Defense_Pierce": 0.45664,
            "Defense_Blunt": 0.7282,
            "Element_Fire": 0.98986,
            "Element_Water": 1.0,
            "Element_Wind": 0.98377,
            "Element_Earth": 0.41129,
            "Toughness": 434
        },
        {
            "Family": "Metals",
            "Subfamily": "Alloy",
            "Tier": "T4",
            "Material_ID": "W",
            "Name": "Tungsten",
            "Defense_Slash": 0.79167,
            "Defense_Pierce": 0.40157,
            "Defense_Blunt": 0.19286,
            "Element_Fire": 0.73454,
            "Element_Water": 1.0,
            "Element_Wind": 0.71429,
            "Element_Earth": 0.71218,
            "Toughness": 980
        },
        {
            "Family": "Metals",
            "Subfamily": "Fantasy",
            "Tier": "T5",
            "Material_ID": "Mithril",
            "Name": "Mithril",
            "Defense_Slash": 0.89911,
            "Defense_Pierce": 0.67344,
            "Defense_Blunt": 0.73296,
            "Element_Fire": 0.85797,
            "Element_Water": 1.0,
            "Element_Wind": 0.69805,
            "Element_Earth": 0.5034,
            "Toughness": 1500
        },
        {
            "Family": "Metals",
            "Subfamily": "Fantasy",
            "Tier": "T5",
            "Material_ID": "Adamantite",
            "Name": "Adamantite",
            "Defense_Slash": 1.0,
            "Defense_Pierce": 0.88281,
            "Defense_Blunt": 0.59323,
            "Element_Fire": 0.85488,
            "Element_Water": 0.93333,
            "Element_Wind": 0.89286,
            "Element_Earth": 0.68351,
            "Toughness": 2500
        },
        {
            "Family": "Metals",
            "Subfamily": "Fantasy",
            "Tier": "T5",
            "Material_ID": "Orichalcum",
            "Name": "Orichalcum",
            "Defense_Slash": 0.83259,
            "Defense_Pierce": 0.67422,
            "Defense_Blunt": 0.65785,
            "Element_Fire": 0.9087,
            "Element_Water": 1.0,
            "Element_Wind": 0.61688,
            "Element_Earth": 0.60306,
            "Toughness": 2000
        },
        {
            "Family": "Organics",
            "Subfamily": "Wood",
            "Tier": "T1",
            "Name": "Pine/Cedar",
            "Defense_Slash": 0.18387,
            "Defense_Pierce": 0.32565,
            "Defense_Blunt": 0.36301,
            "Element_Fire": 0.54312,
            "Element_Water": 0.1,
            "Element_Wind": 0.5,
            "Element_Earth": 0.13232
        },
        {
            "Family": "Organics",
            "Subfamily": "Wood",
            "Tier": "T2",
            "Name": "Oak/Ash/Maple",
            "Defense_Slash": 0.45967,
            "Defense_Pierce": 0.55008,
            "Defense_Blunt": 0.40525,
            "Element_Fire": 0.49562,
            "Element_Water": 0.2,
            "Element_Wind": 0.5,
            "Element_Earth": 0.29251
        },
        {
            "Family": "Organics",
            "Subfamily": "Wood",
            "Tier": "T3",
            "Name": "Hickory/Ebony/Ironwood",
            "Defense_Slash": 0.70518,
            "Defense_Pierce": 0.71339,
            "Defense_Blunt": 0.47831,
            "Element_Fire": 0.49187,
            "Element_Water": 0.32,
            "Element_Wind": 0.5,
            "Element_Earth": 0.48907
        },
        {
            "Family": "Organics",
            "Subfamily": "Wood",
            "Tier": "T4",
            "Name": "Lignum Vitae/Snakewood",
            "Defense_Slash": 0.85875,
            "Defense_Pierce": 0.8156,
            "Defense_Blunt": 0.52055,
            "Element_Fire": 0.56812,
            "Element_Water": 0.68,
            "Element_Wind": 0.5,
            "Element_Earth": 0.65564
        },
        {
            "Family": "Organics",
            "Subfamily": "Wood",
            "Tier": "T5",
            "Name": "Worldtree Yew",
            "Defense_Slash": 0.98151,
            "Defense_Pierce": 0.91781,
            "Defense_Blunt": 0.53196,
            "Element_Fire": 0.7375,
            "Element_Water": 1.0,
            "Element_Wind": 0.5,
            "Element_Earth": 0.64966
        },
        {
            "Family": "Organics",
            "Subfamily": "Leather",
            "Tier": "T1",
            "Name": "Goat/Sheep Hide",
            "Defense_Slash": 0.20884,
            "Defense_Pierce": 0.09583,
            "Defense_Blunt": 0.66073,
            "Element_Fire": 0.40812,
            "Element_Water": 0.21333,
            "Element_Wind": 0.5,
            "Element_Earth": 0.29656
        },
        {
            "Family": "Organics",
            "Subfamily": "Leather",
            "Tier": "T2",
            "Name": "Cowhide/Pigskin",
            "Defense_Slash": 0.37464,
            "Defense_Pierce": 0.17327,
            "Defense_Blunt": 0.74817,
            "Element_Fire": 0.40437,
            "Element_Water": 0.32,
            "Element_Wind": 0.5,
            "Element_Earth": 0.40994
        },
        {
            "Family": "Organics",
            "Subfamily": "Leather",
            "Tier": "T3",
            "Name": "Crocodile/Ostrich",
            "Defense_Slash": 0.52184,
            "Defense_Pierce": 0.26088,
            "Defense_Blunt": 0.80731,
            "Element_Fire": 0.40062,
            "Element_Water": 0.44,
            "Element_Wind": 0.5,
            "Element_Earth": 0.48907
        },
        {
            "Family": "Organics",
            "Subfamily": "Leather",
            "Tier": "T4",
            "Name": "Buffalo/Rhino",
            "Defense_Slash": 0.66904,
            "Defense_Pierce": 0.34849,
            "Defense_Blunt": 0.86644,
            "Element_Fire": 0.35687,
            "Element_Water": 0.45333,
            "Element_Wind": 0.5,
            "Element_Earth": 0.5682
        },
        {
            "Family": "Organics",
            "Subfamily": "Leather",
            "Tier": "T5",
            "Name": "Dragonhide",
            "Defense_Slash": 0.85928,
            "Defense_Pierce": 0.45038,
            "Defense_Blunt": 0.95388,
            "Element_Fire": 0.67188,
            "Element_Water": 0.95,
            "Element_Wind": 0.5,
            "Element_Earth": 0.68158
        },
        {
            "Family": "Organics",
            "Subfamily": "Fur",
            "Tier": "T1",
            "Name": "Fox Fur",
            "Defense_Slash": 0.0,
            "Defense_Pierce": 0.0,
            "Defense_Blunt": 0.55,
            "Element_Fire": 0.25,
            "Element_Water": 0.15,
            "Element_Wind": 0.95,
            "Element_Earth": 0.5
        },
        {
            "Family": "Organics",
            "Subfamily": "Fur",
            "Tier": "T1",
            "Name": "Rabbit or Hare Fur",
            "Defense_Slash": 0.0,
            "Defense_Pierce": 0.0,
            "Defense_Blunt": 0.55,
            "Element_Fire": 0.2,
            "Element_Water": 0.13,
            "Element_Wind": 0.95,
            "Element_Earth": 0.4
        },
        {
            "Family": "Organics",
            "Subfamily": "Fur",
            "Tier": "T2",
            "Name": "Wolf/Deer",
            "Defense_Slash": 0.12913,
            "Defense_Pierce": 0.037078,
            "Defense_Blunt": 0.64196,
            "Element_Fire": 0.67437,
            "Element_Water": 0.096667,
            "Element_Wind": 0.5,
            "Element_Earth": 0.11338
        },
        {
            "Family": "Organics",
            "Subfamily": "Fur",
            "Tier": "T3",
            "Name": "Bear/Bison",
            "Defense_Slash": 0.27049,
            "Defense_Pierce": 0.086377,
            "Defense_Blunt": 0.73393,
            "Element_Fire": 0.6925,
            "Element_Water": 0.2,
            "Element_Wind": 0.5,
            "Element_Earth": 0.22676
        },
        {
            "Family": "Organics",
            "Subfamily": "Fur",
            "Tier": "T4",
            "Name": "Polar Bear/Musk Ox",
            "Defense_Slash": 0.39962,
            "Defense_Pierce": 0.12346,
            "Defense_Blunt": 0.82589,
            "Element_Fire": 0.75437,
            "Element_Water": 0.31,
            "Element_Wind": 0.5,
            "Element_Earth": 0.33588
        },
        {
            "Family": "Organics",
            "Subfamily": "Fur",
            "Tier": "T5",
            "Name": "Phoenix Down",
            "Defense_Slash": 0.61484,
            "Defense_Pierce": 0.18498,
            "Defense_Blunt": 0.9795,
            "Element_Fire": 0.97812,
            "Element_Water": 0.95,
            "Element_Wind": 0.5,
            "Element_Earth": 0.49435
        },
        {
            "Family": "Organics",
            "Subfamily": "Silk",
            "Tier": "T1",
            "Name": "Mulberry Silk",
            "Defense_Slash": 0.15358,
            "Defense_Pierce": 0.26454,
            "Defense_Blunt": 0.39384,
            "Element_Fire": 0.87812,
            "Element_Water": 0.63333,
            "Element_Wind": 0.5,
            "Element_Earth": 0.34742
        },
        {
            "Family": "Organics",
            "Subfamily": "Silk",
            "Tier": "T2",
            "Name": "Tussar/Eri/Muga",
            "Defense_Slash": 0.23967,
            "Defense_Pierce": 0.30953,
            "Defense_Blunt": 0.43037,
            "Element_Fire": 0.89812,
            "Element_Water": 0.69667,
            "Element_Wind": 0.5,
            "Element_Earth": 0.42017
        },
        {
            "Family": "Organics",
            "Subfamily": "Silk",
            "Tier": "T3",
            "Name": "Spider Silk",
            "Defense_Slash": 0.46073,
            "Defense_Pierce": 0.42785,
            "Defense_Blunt": 0.52854,
            "Element_Fire": 0.91813,
            "Element_Water": 0.78,
            "Element_Wind": 0.5,
            "Element_Earth": 0.56354
        },
        {
            "Family": "Organics",
            "Subfamily": "Silk",
            "Tier": "T4",
            "Name": "Giant Spider Silk",
            "Defense_Slash": 0.65097,
            "Defense_Pierce": 0.56673,
            "Defense_Blunt": 0.57078,
            "Element_Fire": 0.93812,
            "Element_Water": 0.845,
            "Element_Wind": 0.5,
            "Element_Earth": 0.66628
        },
        {
            "Family": "Organics",
            "Subfamily": "Silk",
            "Tier": "T5",
            "Name": "Arachne/Starlight Weave",
            "Defense_Slash": 0.81667,
            "Defense_Pierce": 0.69338,
            "Defense_Blunt": 0.60068,
            "Element_Fire": 1.0,
            "Element_Water": 1.0,
            "Element_Wind": 0.5,
            "Element_Earth": 0.75532
        },
        {
            "Family": "Organics",
            "Subfamily": "Scale",
            "Tier": "T1",
            "Name": "Snake/Lizard",
            "Defense_Slash": 0.1472,
            "Defense_Pierce": 0.10405,
            "Defense_Blunt": 0.58904,
            "Element_Fire": 0.52812,
            "Element_Water": 0.65,
            "Element_Wind": 0.5,
            "Element_Earth": 0.2919
        },
        {
            "Family": "Organics",
            "Subfamily": "Scale",
            "Tier": "T2",
            "Name": "Carp/Salmon",
            "Defense_Slash": 0.25773,
            "Defense_Pierce": 0.15705,
            "Defense_Blunt": 0.64566,
            "Element_Fire": 0.43875,
            "Element_Water": 0.715,
            "Element_Wind": 0.5,
            "Element_Earth": 0.38167
        },
        {
            "Family": "Organics",
            "Subfamily": "Scale",
            "Tier": "T3",
            "Name": "Crocodile/Alligator",
            "Defense_Slash": 0.52184,
            "Defense_Pierce": 0.27321,
            "Defense_Blunt": 0.79224,
            "Element_Fire": 0.39312,
            "Element_Water": 0.78,
            "Element_Wind": 0.5,
            "Element_Earth": 0.57418
        },
        {
            "Family": "Organics",
            "Subfamily": "Scale",
            "Tier": "T4",
            "Name": "Pangolin/Armadillo",
            "Defense_Slash": 0.66904,
            "Defense_Pierce": 0.36082,
            "Defense_Blunt": 0.85137,
            "Element_Fire": 0.36937,
            "Element_Water": 0.845,
            "Element_Wind": 0.5,
            "Element_Earth": 0.65331
        },
        {
            "Family": "Organics",
            "Subfamily": "Scale",
            "Tier": "T5",
            "Name": "Dragon Scales",
            "Defense_Slash": 0.85928,
            "Defense_Pierce": 0.46682,
            "Defense_Blunt": 0.93379,
            "Element_Fire": 0.7375,
            "Element_Water": 1.0,
            "Element_Wind": 0.5,
            "Element_Earth": 0.68158
        },
        {
            "Family": "Organics",
            "Subfamily": "Bone",
            "Tier": "T1",
            "Name": "Chicken/Rabbit",
            "Defense_Slash": 0.061111,
            "Defense_Pierce": 0.30563,
            "Defense_Blunt": 0.25114,
            "Element_Fire": 0.18937,
            "Element_Water": 0.26,
            "Element_Wind": 0.5,
            "Element_Earth": 0.24468
        },
        {
            "Family": "Organics",
            "Subfamily": "Bone",
            "Tier": "T2",
            "Name": "Deer/Goat",
            "Defense_Slash": 0.22691,
            "Defense_Pierce": 0.42006,
            "Defense_Blunt": 0.29338,
            "Element_Fire": 0.22937,
            "Element_Water": 0.39,
            "Element_Wind": 0.5,
            "Element_Earth": 0.38997
        },
        {
            "Family": "Organics",
            "Subfamily": "Bone",
            "Tier": "T3",
            "Name": "Cow/Horse/Bison",
            "Defense_Slash": 0.39271,
            "Defense_Pierce": 0.53449,
            "Defense_Blunt": 0.33562,
            "Element_Fire": 0.22562,
            "Element_Water": 0.52,
            "Element_Wind": 0.5,
            "Element_Earth": 0.57782
        },
        {
            "Family": "Organics",
            "Subfamily": "Bone",
            "Tier": "T4",
            "Name": "Whale/Elephant/Rhino",
            "Defense_Slash": 0.55851,
            "Defense_Pierce": 0.64892,
            "Defense_Blunt": 0.37785,
            "Element_Fire": 0.2,
            "Element_Water": 0.65,
            "Element_Wind": 0.5,
            "Element_Earth": 0.74439
        },
        {
            "Family": "Organics",
            "Subfamily": "Bone",
            "Tier": "T5",
            "Name": "Titanbone",
            "Defense_Slash": 0.8104,
            "Defense_Pierce": 0.82889,
            "Defense_Blunt": 0.43151,
            "Element_Fire": 0.45312,
            "Element_Water": 1.0,
            "Element_Wind": 0.5,
            "Element_Earth": 0.97945
        },
        {
            "Family": "Rocks",
            "Subfamily": "Rock",
            "Tier": "T1",
            "Name": "Sandstone",
            "Defense_Slash": 0.0,
            "Defense_Pierce": 0.0,
            "Defense_Blunt": 0.55,
            "Element_Fire": 0.25,
            "Element_Water": 0.07,
            "Element_Wind": 1.0,
            "Element_Earth": 0.25
        },
        {
            "Family": "Rocks",
            "Subfamily": "Rock",
            "Tier": "T2",
            "Name": "Limestone",
            "Defense_Slash": 0.087143,
            "Defense_Pierce": 0.13,
            "Defense_Blunt": 0.49048,
            "Element_Fire": 0.29167,
            "Element_Water": 0.0,
            "Element_Wind": 0.5,
            "Element_Earth": 0.34821
        },
        {
            "Family": "Rocks",
            "Subfamily": "Rock",
            "Tier": "T3",
            "Name": "Granite",
            "Defense_Slash": 0.51357,
            "Defense_Pierce": 0.61,
            "Defense_Blunt": 0.40357,
            "Element_Fire": 0.16,
            "Element_Water": 0.53333,
            "Element_Wind": 0.5,
            "Element_Earth": 0.45536
        },
        {
            "Family": "Rocks",
            "Subfamily": "Rock",
            "Tier": "T4",
            "Name": "Basalt",
            "Defense_Slash": 0.52286,
            "Defense_Pierce": 0.63,
            "Defense_Blunt": 0.37619,
            "Element_Fire": 0.725,
            "Element_Water": 0.66667,
            "Element_Wind": 0.5,
            "Element_Earth": 0.71429
        },
        {
            "Family": "Rocks",
            "Subfamily": "Fantasy",
            "Tier": "T5",
            "Name": "Worldstone",
            "Defense_Slash": 1.0,
            "Defense_Pierce": 1.0,
            "Defense_Blunt": 0.45,
            "Element_Fire": 1.0,
            "Element_Water": 1.0,
            "Element_Wind": 0.5,
            "Element_Earth": 0.875
        },
        {
            "Family": "Minerals",
            "Subfamily": "Mineral",
            "Tier": "T1",
            "Name": "Quartz",
            "Defense_Slash": 0.41346,
            "Defense_Pierce": 0.36046,
            "Defense_Blunt": 0.59811,
            "Element_Fire": 0.8615,
            "Element_Water": 0.93333,
            "Element_Wind": 0.5,
            "Element_Earth": 0.16049
        },
        {
            "Family": "Minerals",
            "Subfamily": "Mineral",
            "Tier": "T2",
            "Name": "Calcite",
            "Defense_Slash": 0.05,
            "Defense_Pierce": 0.025,
            "Defense_Blunt": 0.56944,
            "Element_Fire": 0.64514,
            "Element_Water": 0.0,
            "Element_Wind": 0.5,
            "Element_Earth": 0.15123
        },
        {
            "Family": "Minerals",
            "Subfamily": "Mineral",
            "Tier": "T3",
            "Name": "Obsidian",
            "Defense_Slash": 0.21154,
            "Defense_Pierce": 0.21154,
            "Defense_Blunt": 0.55,
            "Element_Fire": 1.0,
            "Element_Water": 1.0,
            "Element_Wind": 0.5,
            "Element_Earth": 0.0
        },
        {
            "Family": "Minerals",
            "Subfamily": "Mineral",
            "Tier": "T4",
            "Name": "Corundum (Ruby/Sapphire)",
            "Defense_Slash": 0.55769,
            "Defense_Pierce": 0.85769,
            "Defense_Blunt": 0.17222,
            "Element_Fire": 0.3,
            "Element_Water": 1.0,
            "Element_Wind": 0.5,
            "Element_Earth": 0.55556
        },
        {
            "Family": "Minerals",
            "Subfamily": "Fantasy",
            "Tier": "T5",
            "Name": "Aethercrystal",
            "Defense_Slash": 1.0,
            "Defense_Pierce": 1.0,
            "Defense_Blunt": 0.45,
            "Element_Fire": 0.98025,
            "Element_Water": 1.0,
            "Element_Wind": 0.5,
            "Element_Earth": 0.71605
        }
    ]
}
'''

data = json.loads(json_data)
materials = data["materials"]

db = {
    "Cloth": {},
    "Leather": {},
    "Scales": {},
    "Wood": {},
    "Metals": {},
    "Minerals": {}
}

family_map = {
    "Metals": "Metals",
    "Minerals": "Minerals",
    "Rocks": "Minerals",
}

subfamily_map = {
    "Wood": "Wood",
    "Leather": "Leather",
    "Scale": "Scales",
    "Fur": "Cloth",
    "Silk": "Cloth"
}

for mat in materials:
    category = None
    if mat["Family"] in family_map:
        category = family_map[mat["Family"]]
    elif mat["Family"] == "Organics":
        if mat.get("Subfamily") in subfamily_map:
            category = subfamily_map[mat["Subfamily"]]

    if category:
        tier = mat["Tier"]
        if tier not in db[category]:
            db[category][tier] = []

        new_mat = {
            "name": mat["Name"],
            "slash": round(mat.get("Defense_Slash", 0), 5),
            "pierce": round(mat.get("Defense_Pierce", 0), 5),
            "blunt": round(mat.get("Defense_Blunt", 0), 5),
            "fire": round(mat.get("Element_Fire", 0), 5),
            "water": round(mat.get("Element_Water", 0), 5),
            "wind": round(mat.get("Element_Wind", 0), 5),
            "earth": round(mat.get("Element_Earth", 0), 5),
            "toughness": mat.get("Toughness", 0)
        }
        db[category][tier].append(new_mat)

with open('public/db.json', 'w') as f:
    json.dump(db, f, indent=2)

print("Successfully created public/db.json")
